CREATE TABLE `address_concentration_stats` (
	`source_id` text NOT NULL,
	`granularity` text NOT NULL,
	`bucket_start` integer NOT NULL,
	`bucket_end` integer NOT NULL,
	`ip_version` integer NOT NULL,
	`src_locality` text NOT NULL,
	`dst_locality` text NOT NULL,
	`address_side` text NOT NULL,
	`measure` text NOT NULL,
	`weight_total` real NOT NULL,
	`entry_count` integer NOT NULL,
	`hhi` real,
	`top1_share` real,
	`top10_share` real,
	`top100_share` real,
	`entropy_p8` real,
	`entropy_p16` real,
	`entropy_p24` real,
	`entropy_p32` real,
	`entropy_p48` real,
	`entropy_p64` real,
	`entropy_p128` real,
	CONSTRAINT "address_concentration_stats_granularity_check" CHECK("granularity" IN ('5m', '10m', '30m', '1h', '1d')),
	CONSTRAINT "address_concentration_stats_bucket_check" CHECK("bucket_end" > "bucket_start"),
	CONSTRAINT "address_concentration_stats_ip_version_check" CHECK("ip_version" IN (4, 6)),
	CONSTRAINT "address_concentration_stats_src_locality_check" CHECK("src_locality" IN ('all', 'internal', 'external')),
	CONSTRAINT "address_concentration_stats_dst_locality_check" CHECK("dst_locality" IN ('all', 'internal', 'external')),
	CONSTRAINT "address_concentration_stats_address_side_check" CHECK("address_side" IN ('source', 'destination')),
	CONSTRAINT "address_concentration_stats_measure_check" CHECK("measure" IN ('addresses', 'packets', 'bytes')),
	CONSTRAINT "address_concentration_stats_weight_total_check" CHECK("weight_total" >= 0 AND "weight_total" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entry_count_check" CHECK("entry_count" >= 0),
	CONSTRAINT "address_concentration_stats_empty_weight_check" CHECK(("entry_count" = 0) = ("weight_total" = 0)),
	CONSTRAINT "address_concentration_stats_minimum_count_check" CHECK(("hhi" IS NOT NULL) = ("entry_count" >= 2)),
	CONSTRAINT "address_concentration_stats_hhi_check" CHECK("hhi" > 0 AND "hhi" <= 1),
	CONSTRAINT "address_concentration_stats_top1_share_check" CHECK("top1_share" >= 0 AND "top1_share" <= 1),
	CONSTRAINT "address_concentration_stats_top10_share_check" CHECK("top10_share" >= 0 AND "top10_share" <= 1),
	CONSTRAINT "address_concentration_stats_top100_share_check" CHECK("top100_share" >= 0 AND "top100_share" <= 1),
	CONSTRAINT "address_concentration_stats_entropy_p8_check" CHECK("entropy_p8" >= 0 AND "entropy_p8" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entropy_p16_check" CHECK("entropy_p16" >= 0 AND "entropy_p16" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entropy_p24_check" CHECK("entropy_p24" >= 0 AND "entropy_p24" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entropy_p32_check" CHECK("entropy_p32" >= 0 AND "entropy_p32" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entropy_p48_check" CHECK("entropy_p48" >= 0 AND "entropy_p48" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entropy_p64_check" CHECK("entropy_p64" >= 0 AND "entropy_p64" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_entropy_p128_check" CHECK("entropy_p128" >= 0 AND "entropy_p128" <= 1.7976931348623157e308),
	CONSTRAINT "address_concentration_stats_top1_share_presence_check" CHECK(("top1_share" IS NULL) = ("hhi" IS NULL)),
	CONSTRAINT "address_concentration_stats_top10_share_presence_check" CHECK(("top10_share" IS NULL) = ("hhi" IS NULL)),
	CONSTRAINT "address_concentration_stats_top100_share_presence_check" CHECK(("top100_share" IS NULL) = ("hhi" IS NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p32_presence_check" CHECK(("entropy_p32" IS NULL) = ("hhi" IS NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p8_presence_check" CHECK(("entropy_p8" IS NOT NULL) = ("ip_version" = 4 AND "hhi" IS NOT NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p16_presence_check" CHECK(("entropy_p16" IS NOT NULL) = ("ip_version" = 4 AND "hhi" IS NOT NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p24_presence_check" CHECK(("entropy_p24" IS NOT NULL) = ("ip_version" = 4 AND "hhi" IS NOT NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p48_presence_check" CHECK(("entropy_p48" IS NOT NULL) = ("ip_version" = 6 AND "hhi" IS NOT NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p64_presence_check" CHECK(("entropy_p64" IS NOT NULL) = ("ip_version" = 6 AND "hhi" IS NOT NULL)),
	CONSTRAINT "address_concentration_stats_entropy_p128_presence_check" CHECK(("entropy_p128" IS NOT NULL) = ("ip_version" = 6 AND "hhi" IS NOT NULL)),
	CONSTRAINT "address_concentration_stats_top_order_check" CHECK("top10_share" >= "top1_share" AND "top100_share" >= "top10_share")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `idx_address_concentration_stats_key` ON `address_concentration_stats` (`source_id`,`granularity`,`src_locality`,`dst_locality`,`ip_version`,`measure`,`bucket_start`,`address_side`);--> statement-breakpoint
CREATE INDEX `idx_address_concentration_stats_bucket` ON `address_concentration_stats` (`granularity`,`bucket_start`);